# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from src.models.base_model_ import Model
from src import util


class InputText(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, ticker: str=None):  # noqa: E501
        """InputText - a model defined in Swagger

        :param ticker: The ticker of this InputText.  # noqa: E501
        :type ticker: str
        """
        self.swagger_types = {
            'ticker': str
        }

        self.attribute_map = {
            'ticker': 'ticker'
        }

        self._ticker = ticker

    @classmethod
    def from_dict(cls, dikt) -> 'InputText':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InputText of this InputText.  # noqa: E501
        :rtype: InputText
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ticker(self) -> str:
        """Gets the ticker of this InputText.


        :return: The ticker of this InputText.
        :rtype: str
        """
        return self._ticker

    @ticker.setter
    def ticker(self, ticker: str):
        """Sets the ticker of this InputText.


        :param ticker: The ticker of this InputText.
        :type ticker: str
        """

        self._ticker = ticker
