# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from src.models.base_model_ import Model
from src import util


class ResponseObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, company_name: str=None, company_ticker: str=None, debt_to_equity_ratio: float=None, dividend_cagr: object=None, dividend_increase: bool=None, dividend_payout_ratio: object=None, dividend_yield: float=None, price_to_earnings_ratio: float=None, star_rating: str=None, stock_discount: float=None, stock_fair_value: float=None, stock_price: float=None):  # noqa: E501
        """ResponseObject - a model defined in Swagger

        :param company_name: The company_name of this ResponseObject.  # noqa: E501
        :type company_name: str
        :param company_ticker: The company_ticker of this ResponseObject.  # noqa: E501
        :type company_ticker: str
        :param debt_to_equity_ratio: The debt_to_equity_ratio of this ResponseObject.  # noqa: E501
        :type debt_to_equity_ratio: float
        :param dividend_cagr: The dividend_cagr of this ResponseObject.  # noqa: E501
        :type dividend_cagr: object
        :param dividend_increase: The dividend_increase of this ResponseObject.  # noqa: E501
        :type dividend_increase: bool
        :param dividend_payout_ratio: The dividend_payout_ratio of this ResponseObject.  # noqa: E501
        :type dividend_payout_ratio: object
        :param dividend_yield: The dividend_yield of this ResponseObject.  # noqa: E501
        :type dividend_yield: float
        :param price_to_earnings_ratio: The price_to_earnings_ratio of this ResponseObject.  # noqa: E501
        :type price_to_earnings_ratio: float
        :param star_rating: The star_rating of this ResponseObject.  # noqa: E501
        :type star_rating: str
        :param stock_discount: The stock_discount of this ResponseObject.  # noqa: E501
        :type stock_discount: float
        :param stock_fair_value: The stock_fair_value of this ResponseObject.  # noqa: E501
        :type stock_fair_value: float
        :param stock_price: The stock_price of this ResponseObject.  # noqa: E501
        :type stock_price: float
        """
        self.swagger_types = {
            'company_name': str,
            'company_ticker': str,
            'debt_to_equity_ratio': float,
            'dividend_cagr': object,
            'dividend_increase': bool,
            'dividend_payout_ratio': object,
            'dividend_yield': float,
            'price_to_earnings_ratio': float,
            'star_rating': str,
            'stock_discount': float,
            'stock_fair_value': float,
            'stock_price': float
        }

        self.attribute_map = {
            'company_name': 'companyName',
            'company_ticker': 'companyTicker',
            'debt_to_equity_ratio': 'debtToEquityRatio',
            'dividend_cagr': 'dividendCAGR',
            'dividend_increase': 'dividendIncrease',
            'dividend_payout_ratio': 'dividendPayoutRatio',
            'dividend_yield': 'dividendYield',
            'price_to_earnings_ratio': 'priceToEarningsRatio',
            'star_rating': 'starRating',
            'stock_discount': 'stockDiscount',
            'stock_fair_value': 'stockFairValue',
            'stock_price': 'stockPrice'
        }

        self._company_name = company_name
        self._company_ticker = company_ticker
        self._debt_to_equity_ratio = debt_to_equity_ratio
        self._dividend_cagr = dividend_cagr
        self._dividend_increase = dividend_increase
        self._dividend_payout_ratio = dividend_payout_ratio
        self._dividend_yield = dividend_yield
        self._price_to_earnings_ratio = price_to_earnings_ratio
        self._star_rating = star_rating
        self._stock_discount = stock_discount
        self._stock_fair_value = stock_fair_value
        self._stock_price = stock_price

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseObject of this ResponseObject.  # noqa: E501
        :rtype: ResponseObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def company_name(self) -> str:
        """Gets the company_name of this ResponseObject.

        Company name  # noqa: E501

        :return: The company_name of this ResponseObject.
        :rtype: str
        """
        return self._company_name

    @company_name.setter
    def company_name(self, company_name: str):
        """Sets the company_name of this ResponseObject.

        Company name  # noqa: E501

        :param company_name: The company_name of this ResponseObject.
        :type company_name: str
        """

        self._company_name = company_name

    @property
    def company_ticker(self) -> str:
        """Gets the company_ticker of this ResponseObject.

        company ticker  # noqa: E501

        :return: The company_ticker of this ResponseObject.
        :rtype: str
        """
        return self._company_ticker

    @company_ticker.setter
    def company_ticker(self, company_ticker: str):
        """Sets the company_ticker of this ResponseObject.

        company ticker  # noqa: E501

        :param company_ticker: The company_ticker of this ResponseObject.
        :type company_ticker: str
        """

        self._company_ticker = company_ticker

    @property
    def debt_to_equity_ratio(self) -> float:
        """Gets the debt_to_equity_ratio of this ResponseObject.

        Ratio of company's debt to equity  # noqa: E501

        :return: The debt_to_equity_ratio of this ResponseObject.
        :rtype: float
        """
        return self._debt_to_equity_ratio

    @debt_to_equity_ratio.setter
    def debt_to_equity_ratio(self, debt_to_equity_ratio: float):
        """Sets the debt_to_equity_ratio of this ResponseObject.

        Ratio of company's debt to equity  # noqa: E501

        :param debt_to_equity_ratio: The debt_to_equity_ratio of this ResponseObject.
        :type debt_to_equity_ratio: float
        """

        self._debt_to_equity_ratio = debt_to_equity_ratio

    @property
    def dividend_cagr(self) -> object:
        """Gets the dividend_cagr of this ResponseObject.

        The annualized dividend's compound growth rate  # noqa: E501

        :return: The dividend_cagr of this ResponseObject.
        :rtype: object
        """
        return self._dividend_cagr

    @dividend_cagr.setter
    def dividend_cagr(self, dividend_cagr: object):
        """Sets the dividend_cagr of this ResponseObject.

        The annualized dividend's compound growth rate  # noqa: E501

        :param dividend_cagr: The dividend_cagr of this ResponseObject.
        :type dividend_cagr: object
        """

        self._dividend_cagr = dividend_cagr

    @property
    def dividend_increase(self) -> bool:
        """Gets the dividend_increase of this ResponseObject.

        Stock continuously increased dividend for 5 years  # noqa: E501

        :return: The dividend_increase of this ResponseObject.
        :rtype: bool
        """
        return self._dividend_increase

    @dividend_increase.setter
    def dividend_increase(self, dividend_increase: bool):
        """Sets the dividend_increase of this ResponseObject.

        Stock continuously increased dividend for 5 years  # noqa: E501

        :param dividend_increase: The dividend_increase of this ResponseObject.
        :type dividend_increase: bool
        """

        self._dividend_increase = dividend_increase

    @property
    def dividend_payout_ratio(self) -> object:
        """Gets the dividend_payout_ratio of this ResponseObject.

        Annualized dividend divided by earnings per share  # noqa: E501

        :return: The dividend_payout_ratio of this ResponseObject.
        :rtype: object
        """
        return self._dividend_payout_ratio

    @dividend_payout_ratio.setter
    def dividend_payout_ratio(self, dividend_payout_ratio: object):
        """Sets the dividend_payout_ratio of this ResponseObject.

        Annualized dividend divided by earnings per share  # noqa: E501

        :param dividend_payout_ratio: The dividend_payout_ratio of this ResponseObject.
        :type dividend_payout_ratio: object
        """

        self._dividend_payout_ratio = dividend_payout_ratio

    @property
    def dividend_yield(self) -> float:
        """Gets the dividend_yield of this ResponseObject.

        Current dividend yield  # noqa: E501

        :return: The dividend_yield of this ResponseObject.
        :rtype: float
        """
        return self._dividend_yield

    @dividend_yield.setter
    def dividend_yield(self, dividend_yield: float):
        """Sets the dividend_yield of this ResponseObject.

        Current dividend yield  # noqa: E501

        :param dividend_yield: The dividend_yield of this ResponseObject.
        :type dividend_yield: float
        """

        self._dividend_yield = dividend_yield

    @property
    def price_to_earnings_ratio(self) -> float:
        """Gets the price_to_earnings_ratio of this ResponseObject.

        Share price divided by earnings per share  # noqa: E501

        :return: The price_to_earnings_ratio of this ResponseObject.
        :rtype: float
        """
        return self._price_to_earnings_ratio

    @price_to_earnings_ratio.setter
    def price_to_earnings_ratio(self, price_to_earnings_ratio: float):
        """Sets the price_to_earnings_ratio of this ResponseObject.

        Share price divided by earnings per share  # noqa: E501

        :param price_to_earnings_ratio: The price_to_earnings_ratio of this ResponseObject.
        :type price_to_earnings_ratio: float
        """

        self._price_to_earnings_ratio = price_to_earnings_ratio

    @property
    def star_rating(self) -> str:
        """Gets the star_rating of this ResponseObject.

        Stock's star rating out of seven stars  # noqa: E501

        :return: The star_rating of this ResponseObject.
        :rtype: str
        """
        return self._star_rating

    @star_rating.setter
    def star_rating(self, star_rating: str):
        """Sets the star_rating of this ResponseObject.

        Stock's star rating out of seven stars  # noqa: E501

        :param star_rating: The star_rating of this ResponseObject.
        :type star_rating: str
        """

        self._star_rating = star_rating

    @property
    def stock_discount(self) -> float:
        """Gets the stock_discount of this ResponseObject.

        Percentage discount of current price from fair value estimate  # noqa: E501

        :return: The stock_discount of this ResponseObject.
        :rtype: float
        """
        return self._stock_discount

    @stock_discount.setter
    def stock_discount(self, stock_discount: float):
        """Sets the stock_discount of this ResponseObject.

        Percentage discount of current price from fair value estimate  # noqa: E501

        :param stock_discount: The stock_discount of this ResponseObject.
        :type stock_discount: float
        """

        self._stock_discount = stock_discount

    @property
    def stock_fair_value(self) -> float:
        """Gets the stock_fair_value of this ResponseObject.

        Stock's fair value estimated using the Graham number  # noqa: E501

        :return: The stock_fair_value of this ResponseObject.
        :rtype: float
        """
        return self._stock_fair_value

    @stock_fair_value.setter
    def stock_fair_value(self, stock_fair_value: float):
        """Sets the stock_fair_value of this ResponseObject.

        Stock's fair value estimated using the Graham number  # noqa: E501

        :param stock_fair_value: The stock_fair_value of this ResponseObject.
        :type stock_fair_value: float
        """

        self._stock_fair_value = stock_fair_value

    @property
    def stock_price(self) -> float:
        """Gets the stock_price of this ResponseObject.

        Stock's price at end of last business day  # noqa: E501

        :return: The stock_price of this ResponseObject.
        :rtype: float
        """
        return self._stock_price

    @stock_price.setter
    def stock_price(self, stock_price: float):
        """Sets the stock_price of this ResponseObject.

        Stock's price at end of last business day  # noqa: E501

        :param stock_price: The stock_price of this ResponseObject.
        :type stock_price: float
        """

        self._stock_price = stock_price
